### ISSUE TITLE
reading from port/comparison bug

### ISSUE THREAD

**Issue by wentam** [retupmoca/bots#20]
In the following program, I'm setting the scan range to 100, reading it back into a register, and comparing it to 10. If the value (100) is less than 10, it then jumps to fire. Theoretically, it shouldn't fire. But it does.

I have tried with both jle and jgr, in case I have it backwards. In both situations it fires.

```
out.ii 0 0    ; throttle
out.ii 14 8   ; scan arc
out.ii 16 100 ; scan range

!main
  in.i 2 16   ; read from radar range (which we have just set to 100)
  cmp.ri 2 10 ; compare
  jgr.i !fire ; fire if 100 < 10 -- yet it fires
jmp.i !main

!fire
int.i 3
jmp.i !main
```

**Comment by retupmoca** [comment]
On my machine, the bots fire with jls, and do not fire with jgr. Did you re-assemble after your change?

**Comment by wentam** [comment]
I messed up the explanation a bit -- with jgr, it will _never_ fire, even if I compare to 200.
With jle, it will _always_ fire, even if I compare to 0.
