### ISSUE TITLE
call/ret ops not functioning

### ISSUE THREAD

**Issue by wentam** [retupmoca/bots#28]
I put a test call in my bot:

```
!test
    int.i 3 ; fire
ret
```

And called it in my main loop:

```
!main
    call.i !test
    [normal bot stuff]
jmp.i !main
```

The bot fires a few shots, then completely freezes up. (without this call, the bot would not be frozen)

When playing with it, I've also had a situation where it caused my tank to move forward, even though I never set the throttle to anything other than 0 in my program.

**Comment by retupmoca** [comment]
Please re-test
